### ISSUE TITLE
send_violations_tests.js seems flaky

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-customs-server#153] opened 2017-01-10 09:16 UTC
Running the tests locally, I get failures at least half the time.  If I just delete `./test/remote/send_violations_tests.js` then they all seem to pass reliably.  Not sure what's going on but maybe some timing issue in those tests interfering with others?

**Comment by vbudhram** [comment] 2017-01-10 15:17
@rfk I think this is a timing issue, in #152 , I am not able to reproduce it because timing rate limit was bumped up to [10ms](https://github.com/g-k/fxa-customs-server/blob/6ccd65bdd66751230c69a1a05227d80407c14221/test/remote/send_violations_tests.js#L28). This should get resolved when that merges.

**Comment by vbudhram** [comment] 2017-01-11 17:29
Ran tests 3 times with no issues using patch. Could be coincidence but we can reopen, closing via #157.

**Closed by vbudhram** 2017-01-11 17:29 UTC
